CREATE TABLE search_history (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    summary  VARCHAR(500) NOT NULL,
    searched_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_search_history_searched_at ON search_history (searched_at DESC);
CREATE INDEX idx_search_history_username    ON search_history (username);
